matrix:
  include:
    # dotnet
    - language: csharp
      mono: none
      dotnet: 2.1.502
      solution: ./dotnet/Thoaded.sln
      before_script:
        - cd dotnet
      script:
        - dotnet test
    # flutter
    - os: linux
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - libstdc++6
            - fonts-droid-fallback
      before_script:
        - cd flutter
        - git clone https://github.com/flutter/flutter.git
        - export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH
        - flutter doctor
      script:
        - flutter test
      cache:
        directories:
          - $HOME/.pub-cache
    # java
    - language: java
      before_script:
        - cd java
      script:
        - mvn test
      jdk:
        - oraclejdk13
    # javascript
    - language: node_js
      node_js:
        - 13
      before_script:
        - cd javascript
        - npm install
        - npm run build
      script:
        - npm run test
    # python
    - language: python
      python: 3.7
      before_script:
        - cd python
      script:
        - python -m unittest thoadedtest.py
    # swift
    - language: swift
      osx_image: xcode11.3
      before_script:
        - cd swift
      script:
        - swift test